application: my-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /api/v1/.*
    script: rest_api_v1.app

  - url: /tests/.*
    script: manual_tests.app
    login: admin

libraries:
- name: jinja2
  version: latest
